# Site
name: "Bytes Pun Here"
title: "Bytes Pun Here"
description: "A collection of recipes from an infosec 'professional'."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /recipes
google_analytics: 'UA-90662247-1'
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  nathaniel:
    name: Nathaniel
    display_name: Nathaniel
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: blog@scriptingis.life
    web: https://scriptingis.life
    twitter: https://twitter.com/scriptingis.life
    description: "Cooking is my meditation. I like to get away from the computer and experiment by creating complex and (sometimes) healthy meals."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
